### ISSUE TITLE
SystemError: tile cannot extend outside image

### ISSUE THREAD

**Issue by viewsourc3** [akselsd/NB.no-Downloader#4]
When I launch the script, I get the following error: 

> Length not specified, calculating book length
> Book length found:  0
> Downloading book 2009041404106_C1
> Traceback (most recent call last):
>   File "\\Mac\Home\Desktop\nbdownload.py", line 167, in <module>
>     main()
>   File "\\Mac\Home\Desktop\nbdownload.py", line 164, in main
>     b.download_book()
>   File "\\Mac\Home\Desktop\nbdownload.py", line 98, in download_book
>     self.download_page("C1", retry)
>   File "\\Mac\Home\Desktop\nbdownload.py", line 64, in download_page
>     page.save(self.id+"_temp_image_folder\\"+str(page_nr)+".jpg")
>   File "C:\Users\cslm\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 2235, in save
>     save_handler(self, fp, filename)
>   File "C:\Users\cslm\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\JpegImagePlugin.py", line 782, in _save
>     ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
>   File "C:\Users\cslm\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\ImageFile.py", line 531, in _save
>     e.setimage(im.im, b)
> SystemError: tile cannot extend outside image

I am running the script through a Windows virtual machine installed on a mac. 

I don't know if I'm entering the wrong book ID or if there's something wrong with the way the script works... :/ 

I appreciate any form of help! 
Thank you,

**Comment by davidrobertsen** [comment]
I also have an issue:

 

> bash:~# python ./nbdownload.py 2008082100028
>  
>   File "./nbdownload.py", line 7
>     <!DOCTYPE html>
>     ^
> SyntaxError: invalid syntax
